# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/samples", skip: "implement later", type: :request do
  let(:ts) { TasteSession.new(name: 'test22') }
  let(:valid_attributes) do
    skip('implement?')
    # {taste_session: ts, reveal_name: 'bottle 1'}
  end

  let(:invalid_attributes) do
    skip("Add a hash of attributes invalid for your model")
  end

  describe "GET /index" do
    it "renders a successful response" do
      Sample.create! valid_attributes
      get taste_session_samples_url(ts)
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      sample = Sample.create! valid_attributes
      get taste_session_sample_url(sample)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_sample_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      sample = Sample.create! valid_attributes
      get edit_sample_url(sample)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Sample" do
        expect {
          post taste_session_samples_url(ts), params: { sample: valid_attributes }
        }.to change(Sample, :count).by(1)
      end

      it "redirects to the created sample" do
        post taste_session_samples_url(ts), params: { sample: valid_attributes }
        expect(response).to redirect_to(sample_url(Sample.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Sample" do
        expect {
          post samples_url, params: { sample: invalid_attributes }
        }.not_to change(Sample, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post samples_url, params: { sample: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        skip("Add a hash of attributes valid for your model")
      end

      it "updates the requested sample" do
        sample = Sample.create! valid_attributes
        patch sample_url(sample), params: { sample: new_attributes }
        sample.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the sample" do
        sample = Sample.create! valid_attributes
        patch sample_url(sample), params: { sample: new_attributes }
        sample.reload
        expect(response).to redirect_to(sample_url(sample))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        sample = Sample.create! valid_attributes
        patch sample_url(sample), params: { sample: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested sample" do
      sample = Sample.create! valid_attributes
      expect {
        delete sample_url(sample)
      }.to change(Sample, :count).by(-1)
    end

    it "redirects to the samples list" do
      sample = Sample.create! valid_attributes
      delete sample_url(sample)
      expect(response).to redirect_to(samples_url)
    end
  end
end
